services:
  - type: worker
    name: shopping-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_render.py
    envVars:
      - key: BOT_TOKEN
        sync: false
