services:
  - type: web
    name: shopping-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_render.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 8000
